Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,62 +1,63 @@
 # This is a basic workflow to help you get started with Actions
-
-name: CI
-env:
-  DOCKER_REPOSITORY: harbor.lan
-
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      - name: Create annotation for build error
-        run: echo "::error file=app.js,line=1::Missing semicolon"
-
-      - name: notification
-        if: cancelled() == false
-        uses: xinthink/action-telegram@v1.1
-        with:
-          botToken: ${{ secrets.TELEGRAM_TOKEN }}
-          chatId: ${{ secrets.TELEGRAM_TO }}
-          jobStatus: ${{ job.status }}
-      - name: exit 1
-        run: exit 1
-
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-          
-      - name: Current date
-        run: |
-          echo 'test'
-          echo "DOCKER_TAG=$(date +%Y%m%dT%H%M)" >> $GITHUB_ENV
-          echo '${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_TAG }}'
-
-      - name: Current date 2
-        run: |
-          echo 'test'
-          echo '${{ env.DOCKER_REPOSITORY }}/${{  github.repository }}${{ env.DOCKER_TAG }}'
+#
+# name: CI
+# env:
+#   DOCKER_REPOSITORY: harbor.lan
+#
+# # Controls when the workflow will run
+# on:
+#   # Triggers the workflow on push or pull request events but only for the "main" branch
+#   push:
+#     branches: [ "main" ]
+#   pull_request:
+#     branches: [ "main" ]
+#
+#   # Allows you to run this workflow manually from the Actions tab
+#   workflow_dispatch:
+#
+# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# jobs:
+#   # This workflow contains a single job called "build"
+#   build:
+#     # The type of runner that the job will run on
+#     runs-on: ubuntu-latest
+#
+#     # Steps represent a sequence of tasks that will be executed as part of the job
+#     steps:
+#       - name: Create annotation for build error
+#         run: echo "::error file=app.js,line=1::Missing semicolon"
+#
+#       - name: notification
+#         if: cancelled() == false
+#         uses: xinthink/action-telegram@v1.1
+#         with:
+#           botToken: ${{ secrets.TELEGRAM_TOKEN }}
+#           chatId: ${{ secrets.TELEGRAM_TO }}
+#           jobStatus: ${{ job.status }}
+#       - name: exit 1
+#         run: exit 1
+#
+#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+#       - uses: actions/checkout@v3
+#
+#       # Runs a single command using the runners shell
+#       - name: Run a one-line script
+#         run: echo Hello, world!
+#
+#       # Runs a set of commands using the runners shell
+#       - name: Run a multi-line script
+#         run: |
+#           echo Add other actions to build,
+#           echo test, and deploy your project.
+#
+#       - name: Current date
+#         run: |
+#           echo 'test'
+#           echo "DOCKER_TAG=$(date +%Y%m%dT%H%M)" >> $GITHUB_ENV
+#           echo '${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_TAG }}'
+#
+#       - name: Current date 2
+#         run: |
+#           echo 'test'
+#           echo '${{ env.DOCKER_REPOSITORY }}/${{  github.repository }}${{ env.DOCKER_TAG }}'
+#
